import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { roleService, Role, companyService, Company, permissionService, Feature, PermissionType, RolePermission } from '../api';
import { Plus, Edit2, Trash2, Shield, Check, X } from 'lucide-react';

export default function RolePage() {
  const { t } = useTranslation();
  const [companies, setCompanies] = useState<Company[]>([]);
  const [selectedCompanyId, setSelectedCompanyId] = useState<string>('');
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(false);
  
  // Role Form
  const [showRoleForm, setShowRoleForm] = useState(false);
  const [roleData, setRoleData] = useState<Partial<Role>>({ name: '', description: '', scope_type: 'CUSTOM' });
  const [editingRoleId, setEditingRoleId] = useState<string | null>(null);

  // Permission Matrix
  const [showPermissions, setShowPermissions] = useState(false);
  const [selectedRole, setSelectedRole] = useState<Role | null>(null);
  const [features, setFeatures] = useState<Feature[]>([]);
  const [permTypes, setPermTypes] = useState<PermissionType[]>([]);
  const [rolePerms, setRolePerms] = useState<RolePermission[]>([]);

  useEffect(() => {
    loadCompanies();
    loadMetadata();
  }, []);

  useEffect(() => {
    if (selectedCompanyId) {
      loadRoles(selectedCompanyId);
    }
  }, [selectedCompanyId]);

  const loadMetadata = async () => {
    const [f, p] = await Promise.all([
      permissionService.getFeatures(),
      permissionService.getPermissionTypes()
    ]);
    setFeatures(f);
    setPermTypes(p);
  };

  const loadCompanies = async () => {
    const data = await companyService.getAll();
    setCompanies(data);
    if (data.length > 0) setSelectedCompanyId(data[0].id);
  };

  const loadRoles = async (companyId: string) => {
    setLoading(true);
    try {
      const data = await roleService.getAll(companyId);
      setRoles(data);
    } finally {
      setLoading(false);
    }
  };

  const handleRoleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingRoleId) {
        await roleService.update(editingRoleId, roleData);
      } else {
        await roleService.create(selectedCompanyId, roleData);
      }
      loadRoles(selectedCompanyId);
      setShowRoleForm(false);
      setRoleData({ name: '', description: '', scope_type: 'CUSTOM' });
      setEditingRoleId(null);
    } catch (error) {
      alert(t('common.saveError'));
    }
  };

  const handleDeleteRole = async (id: string) => {
    if (window.confirm(t('common.confirmDelete'))) {
      await roleService.delete(id);
      loadRoles(selectedCompanyId);
    }
  };

  const openPermissions = async (role: Role) => {
    setSelectedRole(role);
    const perms = await permissionService.getRolePermissions(role.id);
    setRolePerms(perms);
    setShowPermissions(true);
  };

  const togglePermission = (featureId: string, permTypeId: string) => {
    const existing = rolePerms.find(p => p.feature_id === featureId && p.permission_type_id === permTypeId);
    let newPerms = [...rolePerms];
    
    if (existing) {
      newPerms = newPerms.map(p => 
        (p.feature_id === featureId && p.permission_type_id === permTypeId)
          ? { ...p, is_allowed: p.is_allowed ? 0 : 1 }
          : p
      );
    } else {
      newPerms.push({
        id: '', // Will be generated by backend
        role_id: selectedRole!.id,
        feature_id: featureId,
        permission_type_id: permTypeId,
        is_allowed: 1
      });
    }
    setRolePerms(newPerms);
  };

  const savePermissions = async () => {
    if (!selectedRole) return;
    try {
      await permissionService.updateRolePermissions(selectedRole.id, rolePerms);
      setShowPermissions(false);
      alert(t('role.saveSuccess'));
    } catch (error) {
      alert(t('role.saveError'));
    }
  };

  const isAllowed = (featureId: string, permTypeId: string) => {
    const perm = rolePerms.find(p => p.feature_id === featureId && p.permission_type_id === permTypeId);
    return perm?.is_allowed === 1;
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">{t('role.title')}</h2>
          <p className="text-gray-500">{t('role.subtitle')}</p>
        </div>
        <div className="flex items-center gap-4">
          <select 
            value={selectedCompanyId} 
            onChange={(e) => setSelectedCompanyId(e.target.value)}
            className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
          >
            {companies.map(c => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
          <button
            onClick={() => { 
              setRoleData({ name: '', description: '', scope_type: 'CUSTOM' }); 
              setEditingRoleId(null); 
              setShowRoleForm(true); 
            }}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
          >
            <Plus size={20} />
            {t('role.add')}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {roles.map(role => (
          <div key={role.id} className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 flex flex-col">
            <div className="flex justify-between items-start mb-4">
              <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
                <Shield size={24} />
              </div>
              <div className="flex gap-2">
                <button 
                  onClick={() => {
                    setRoleData(role);
                    setEditingRoleId(role.id);
                    setShowRoleForm(true);
                  }}
                  className="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded"
                  title={t('common.edit')}
                >
                  <Edit2 size={16} />
                </button>
                <button 
                  onClick={() => handleDeleteRole(role.id)}
                  className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded"
                  title={t('common.delete')}
                >
                  <Trash2 size={16} />
                </button>
              </div>
            </div>
            <h3 className="text-lg font-bold text-gray-900 mb-1">{role.name}</h3>
            <p className="text-sm text-gray-500 mb-4 flex-1">{role.description || t('common.noData')}</p>
            
            <div className="pt-4 border-t border-gray-100">
              <button 
                onClick={() => openPermissions(role)}
                className="w-full py-2 text-sm font-medium text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
              >
                {t('role.managePermissions')}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Role Form Modal */}
      {showRoleForm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-lg w-full max-w-md p-6">
            <h3 className="text-lg font-bold mb-4">{editingRoleId ? t('role.edit') : t('role.new')}</h3>
            <form onSubmit={handleRoleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">{t('role.name')}</label>
                <input
                  type="text"
                  required
                  value={roleData.name}
                  onChange={e => setRoleData({ ...roleData, name: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">{t('role.description')}</label>
                <textarea
                  value={roleData.description}
                  onChange={e => setRoleData({ ...roleData, description: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg"
                  rows={3}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">{t('role.scopeType')}</label>
                <select
                  value={roleData.scope_type}
                  onChange={e => setRoleData({ ...roleData, scope_type: e.target.value as any })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg"
                >
                  <option value="CUSTOM">{t('role.scopes.CUSTOM')}</option>
                  <option value="SELF">{t('role.scopes.SELF')}</option>
                </select>
              </div>
              <div className="flex justify-end gap-3 mt-6">
                <button
                  type="button"
                  onClick={() => setShowRoleForm(false)}
                  className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg"
                >
                  {t('common.cancel')}
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
                >
                  {t('common.save')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Permissions Matrix Modal */}
      {showPermissions && selectedRole && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-lg w-full max-w-4xl p-6 h-[80vh] flex flex-col">
            <div className="flex justify-between items-center mb-6">
              <div>
                <h3 className="text-xl font-bold text-gray-900">{t('role.permissionsTitle', { role: selectedRole.name })}</h3>
                <p className="text-sm text-gray-500">{t('role.permissionsSubtitle')}</p>
              </div>
              <button onClick={() => setShowPermissions(false)} className="p-2 hover:bg-gray-100 rounded-full">
                <X size={24} />
              </button>
            </div>

            <div className="flex-1 overflow-auto border border-gray-200 rounded-lg">
              <table className="w-full text-left border-collapse">
                <thead className="bg-gray-50 sticky top-0 z-10">
                  <tr>
                    <th className="p-4 border-b border-gray-200 font-medium text-gray-500 text-sm">{t('role.feature')}</th>
                    {permTypes.map(pt => (
                      <th key={pt.id} className="p-4 border-b border-gray-200 font-medium text-gray-500 text-sm text-center">
                        {pt.code}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {Object.entries(features.reduce((acc, feature) => {
                    const serviceName = feature.service_name || 'Other';
                    if (!acc[serviceName]) acc[serviceName] = [];
                    acc[serviceName].push(feature);
                    return acc;
                  }, {} as Record<string, Feature[]>)).map(([serviceName, serviceFeatures]: [string, Feature[]]) => (
                    <React.Fragment key={serviceName}>
                      <tr className="bg-gray-100">
                        <td colSpan={permTypes.length + 1} className="p-2 px-4 font-bold text-gray-700 text-xs uppercase tracking-wider">
                          {serviceName}
                        </td>
                      </tr>
                      {serviceFeatures.map(feature => (
                        <tr key={feature.id} className="hover:bg-gray-50">
                          <td className="p-4 text-sm font-medium text-gray-900 pl-8 border-l-4 border-transparent hover:border-indigo-500 transition-colors">
                            {feature.name}
                            <div className="text-xs text-gray-400 font-normal">{feature.code}</div>
                          </td>
                          {permTypes.map(pt => (
                            <td key={pt.id} className="p-4 text-center">
                              <button
                                onClick={() => togglePermission(feature.id, pt.id)}
                                className={`w-6 h-6 rounded border flex items-center justify-center transition-colors mx-auto ${
                                  isAllowed(feature.id, pt.id)
                                    ? 'bg-indigo-600 border-indigo-600 text-white'
                                    : 'bg-white border-gray-300 text-transparent hover:border-indigo-400'
                                }`}
                              >
                                <Check size={14} />
                              </button>
                            </td>
                          ))}
                        </tr>
                      ))}
                    </React.Fragment>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="flex justify-end gap-3 mt-6 pt-4 border-t border-gray-100">
              <button
                onClick={() => setShowPermissions(false)}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg"
              >
                {t('common.cancel')}
              </button>
              <button
                onClick={savePermissions}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
              >
                {t('role.savePermissions')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
